First commit after fork.

diff --git a/run_cmake-osx b/run_cmake-osx
--- a/run_cmake-osx
+++ b/run_cmake-osx
@@ -1,43 +1,36 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
 here=$(cd $(dirname "$0"); /bin/pwd)
 
-# usage: run_cmake-osx [-g]
+# usage: run_cmake-osx [-g] 32|64
 
-tmp=tmp
-buildtype=Release
+tmp="tmp"
+buildtype="Release"
 
-if [[ $1 = -g ]]; then
-    tmp=tmp_debug
-    buildtype=Debug
+if [ "$1" = "-g" ]; then
+    tmp="tmp_debug"
+    buildtype="Debug"
     shift
 fi
-
-os=$(IFS=. read -r a b _ < <(sysctl -n kern.osproductversion); printf "%03d" "$a" "$b")
-sonoma=014000
-cmake_extra_args=()
-if [[ $os > $sonoma || $os == $sonoma ]]; then
-    cmake_extra_args+=(-DCMAKE_OSX_DEPLOYMENT_TARGET=14.0)
-fi
-
-APPLE_ARCH=x86_64
+    
+case "$1" in
+    32)   APPLE_ARCH=i386 ; shift ;;
+    64)   APPLE_ARCH=x86_64 ; shift ;;
+    *)    echo "usage: $0 32|64" >&2; exit 1 ;;
+esac
 
 WXWIN=$(wx-config --prefix)
-[[ -d $WXWIN ]] || {
-    echo "could not find wxWidgets installation" >&2
+[ -d "$WXWIN" ] || {
+    echo "could not find wxWidgets insalltation" >&2
     exit 1
 }
 
-set -e
-
-cd "$here"
-mkdir -p "$tmp"
-cd "$tmp"
+cd $here
+mkdir -p $tmp
+cd $tmp
 
 cmake -G "Unix Makefiles" \
-    -DwxWidgets_PREFIX_DIRECTORY="$WXWIN" \
-    -DAPPLE_ARCH="$APPLE_ARCH" \
-    -DCMAKE_BUILD_TYPE="$buildtype" \
-    "${cmake_extra_args[@]}" \
-    "$@" \
-    ..
+    -DwxWidgets_PREFIX_DIRECTORY=$WXWIN \
+    -DAPPLE_ARCH=$APPLE_ARCH \
+    -DCMAKE_BUILD_TYPE=$buildtype \
+    ${1+"$@"} ..
